production:
  cluster: false
  workers: 1
  redis:
    db: moon
    host: drum.redistogo.com
    port: 9200
    pass: e66582e95e16930b94c7d0597b31dc5e

development:
  cluster: true
  workers: 1
  redis:
    host: localhost